@echo off
cd /d "%~dp0"
ren "images\accessories\1pc Solid Adjustable Size Casual Baseball Cap, Sun….jpg" "baseball-cap.jpg"
ren "images\accessories\Explore Land Cotton Military Shemagh Tactical Desert Keffiyeh Scarf Wrap.jpeg" "military-scarf.jpeg"
ren "images\accessories\Iced Out Cuban Link Necklace - Silver_Gold Hip Hop Chain for Men Women.jpeg" "cuban-necklace.jpeg"
ren "images\accessories\must need jewellery!! featuring @bettyandbiddy….jpeg" "jewellery-set.jpeg"
ren "images\accessories\Cadena Barbada Acero.jpg" "chain.jpg"
ren "images\accessories\classy socks for men.jpg" "mens-socks.jpg"
ren "images\accessories\Aesthetic watch for women.jpeg" "womens-watch.jpeg"
ren "images\accessories\Dimension_ These necklaces are 50 cm_19_6_ in….jpg" "necklace.jpg"
ren "images\accessories\Elevate your wardrobe with this new leather….jpg" "leather-accessory.jpg"
ren "images\accessories\Gender_Women,Men; What's in the box_1 x Watch….jpg" "unisex-watch.jpg"
ren "images\accessories\gwbks                                            ….jpg" "accessory.jpg"
ren "images\accessories\Introducing our elegant Rope Stainless Steel Chain….jpg" "rope-chain.jpg"
ren "images\accessories\My new designs feature gender-neutral rings and….jpg" "neutral-rings.jpg"
ren "images\accessories\New Width 3_4cm Men's Belt Business Formal Real….jpg" "mens-belt.jpg"
ren "images\accessories\PRICES MAY VARY_ Designed & Created Care by Falari….jpg" "falari-design.jpg"
ren "images\accessories\Seiko Astron Watch GPS Solar Dual Time Titanium….jpg" "seiko-watch.jpg"
ren "images\accessories\Sports Medal and Trophy Display.jpg" "sports-medal.jpg"
ren "images\accessories\Stay Comfortable and Stylish with Our Men's….jpg" "mens-comfort.jpg"
ren "images\accessories\The fashionable jeans for men are perfect to wear….jpg" "mens-jeans.jpg"
ren "images\accessories\The Wide Rectangle Signet Ring features a 17mm x….jpg" "signet-ring.jpg"
ren "images\accessories\แว่นตากรอบโลหะแฟชั่นผู้ชาย….jpg" "mens-glasses.jpg"
ren "images\bags and suitcase\CB CITY BAG 17_3 Inch Laptop Bag Computer Bag for Men & Women, Black Laptop Case Sleeve with Shoulder Strap - Document Handbag Briefcase for Work, Office, Travel, or Business.jpeg" "laptop-bag.jpeg"
ren "images\bags and suitcase\Convertible Garment Duffel Bag for Travel - Carry On Garment Bags With Toiletry Bag Large Weekender Bag for Men Women 2 in 1 Hanging Suitcase Suit Travel Duffel Overnight Bags 4pcs Set.jpeg" "garment-bag.jpeg"
ren "images\bags and suitcase\Garment Duffle Bags for Travel,Moulyan Convertible Garment Bag with Shoe Compartment,3 in 1 Waterproof Travel Suit Bag with Shoulder Strap for Men Women.jpeg" "duffle-bag.jpeg"
ren "images\bags and suitcase\KROSER TSA Friendly Laptop Bag 15_6 inch Briefcase Check Point Friendly Laptop Messenger Bag Water Repellent Computer Case with RFID Pockets for College_Business_Women_Men-Charcoal Black.jpeg" "tsa-laptop-bag.jpeg"
ren "images\bags and suitcase\Looking for lightweight traveling bags_  Here’s is….jpeg" "lightweight-bag.jpeg"
ren "images\bags and suitcase\Luggage by-4 N150,000 #luggage.jpeg" "luggage-set.jpeg"
ren "images\bags and suitcase\Luggage set by 4 N90,000 #luggage #boxes.jpeg" "budget-luggage.jpeg"
ren "images\bags and suitcase\THE CONVERTIBLE DUFFLE GARMENT LUGGAGE.jpeg" "convertible-duffle.jpeg"
ren "images\bags and suitcase\This Backpack Has A Secret Feature — And It’s The TSA Hack You Never Knew You Needed.jpeg" "tsa-backpack.jpeg"
ren "images\bags and suitcase\Travel Backpack Men's Business Multifunction Computer Bag Vacuum Compression Large-capacity Backpack - Army Green _ 19 Inch (1).jpeg" "army-backpack.jpeg"
ren "images\bags and suitcase\Travel Backpack Men's Business Multifunction Computer Bag Vacuum Compression Large-capacity Backpack - Army Green _ 19 Inch.jpeg" "large-backpack.jpeg"
ren "images\bags and suitcase\ZHMO Large Canvas Tote Bag for Women,Womens Laptop Work Book Bags Crossbody Purse Handbag Shoulder Travel Messenger Gym Totes.jpeg" "canvas-tote.jpeg"
ren "images\designer bag\Add a unique touch to your formal wear with this….jpg" "formal-accessory.jpg"
ren "images\designer bag\Comfortable Fish Mouth Slip-on Open Toe Fashion….jpg" "fish-mouth-shoes.jpg"
ren "images\designer bag\Corbata de corbatas para hombre, vestido de boda….jpg" "mens-tie.jpg"
ren "images\designer bag\Discover the Advantages of the Jb'S Food Grade….jpg" "food-grade.jpg"
ren "images\designer bag\Elevate your office attire with USS Shoes Raquel….jpg" "office-shoes.jpg"
ren "images\designer bag\Highlights__[Fabric]_ Crafted from high-quality PU….jpg" "pu-fabric.jpg"
ren "images\designer bag\Mocassins Masculinos com Padrão Colorido e….jpg" "colored-mocassins.jpg"
ren "images\designer bag\Nike Heritage Winterized Eugene Backpack (23L)….jpg" "nike-backpack.jpg"
ren "images\designer bag\Oxford shoes are made of full grain leathers with….jpg" "oxford-shoes.jpg"
ren "images\designer bag\PRICES MAY VARY_ Condition_ Classic and High….jpg" "classic-condition.jpg"
ren "images\designer bag\The 530 sneakers feature a segmented ABZORB….jpg" "abzorb-sneakers.jpg"
ren "images\designer bag\The best of DAN & OJOWA brand official wear by….jpg" "dan-ojowa.jpg"
ren "images\designer bag\Yellow Safety Gumboots LL-2-05 Steel toe can be….jpg" "safety-gumboots.jpg"
ren "images\hotel supplies\Cotton Bath Towel Adult Soft Absorbent Towels Bathroom Sets Large Beach Towel Hotel Spa Towels For.jpeg" "cotton-towel.jpeg"
ren "images\hotel supplies\Comfy Bedding _ 5-Piece Comforter Set _ Microfiber Bedding _ Full _ Frame – Gray _ 1 Comforter, 2 Pillow Cases, 1 Square Decorative Pillow & 1 Rectangle Decorative Pillow _ Microfiber _ Modern.jpeg" "comforter-set.jpeg"
ren "images\hotel supplies\UNISEX BATHROBE PURE COTTON KIMONO WAFFLE LIGHTWEIGHT DRESSING GOWN.jpeg" "bathrobe.jpeg"
ren "images\hotel supplies\wholesale Cosmetic Kit Cosmetics Cosmetic Packaging Set Airline Amenity Kit Wholesale.jpeg" "cosmetic-kit.jpeg"
ren "images\kids wear\Suit For Boys Fashion Design Double Breasted Blazer Kids Wedding Tuxedo 2 Piece Set Jacket Pants 2-16 Years Old - AliExpress 1501.jpeg" "boys-suit.jpeg"
ren "images\men fashion\2025 Spring Men's Jeans High Quality Classic Style….jpg" "spring-jeans.jpg"
ren "images\men fashion\Boyfriend Style Men's Striped Patchwork Zipper….jpg" "striped-hoodie.jpg"
ren "images\men fashion\CARACTÉRISTIQUES________ Type de tissu _ Fibre….jpg" "fabric-item.jpg"
ren "images\men fashion\Chemise à manches courtes simple et mode pour….jpg" "short-sleeve-shirt.jpg"
ren "images\men fashion\Christopher Noir™ - The Original_ Where Culture….jpg" "christopher-noir.jpg"
ren "images\men fashion\Description_   Formal Men's Suits 2 Piece Slim Fit….jpg" "slim-suit.jpg"
ren "images\men fashion\Elegant Handmade Navy Blue Three Piece Coat Pant….jpg" "three-piece-suit.jpg"
ren "images\men fashion\Elegantes Herren Anzug Set Königsblau….jpg" "blue-suit.jpg"
ren "images\men fashion\Elevate Your Casual Look with Our Stylish Long….jpg" "long-sleeve.jpg"
ren "images\men fashion\Here's a men's outfit perfect for all your outings….jpg" "outfit.jpg"
ren "images\men fashion\Herren Hochzeit Anzüge Suits Marineblau Armeegrün….jpg" "wedding-suit.jpg"
ren "images\men fashion\Iconic and instantly recognizable, Polo Ralph….jpg" "polo-ralph.jpg"
ren "images\men fashion\Made from a premium blend of wool this Safari suit….jpg" "safari-suit.jpg"
ren "images\men fashion\PRICES MAY VARY_ 【2 PIECE MENS SUIT FABRIC】This….jpg" "2-piece-suit.jpg"
ren "images\men fashion\PRICES MAY VARY_ 【Materials】_The jogging suits….jpg" "jogging-suit.jpg"
ren "images\men fashion\PRICES MAY VARY_ Comfortable Fabrics_Men Athletic….jpg" "athletic-wear.jpg"
ren "images\men fashion\PRICES MAY VARY_ Service --- If you have any….jpg" "service-item.jpg"
ren "images\men fashion\Product information_ Color_ gray, black, blue….jpg" "gray-shirt.jpg"
ren "images\men fashion\Product information_ Pattern_ Plaid Color_ green….jpg" "plaid-shirt.jpg"
ren "images\men fashion\Revamp your sportswear collection with this….jpg" "sportswear.jpg"
ren "images\men fashion\Slim-fit trousers in melange virgin wool_ Elegant….jpg" "slim-trousers.jpg"
ren "images\men fashion\Slim-fit trousers in seersucker_ With front pleats….jpg" "seersucker-trousers.jpg"
ren "images\men fashion\SPECIFICATIONS Plus Size 40 42 44 Autumn Loose….jpg" "plus-size.jpg"
ren "images\men fashion\This short-sleeve tops is made with comfortable….jpg" "short-sleeve-top.jpg"
ren "images\men fashion\Wale African men clothing_embroidered suit_wedding suit_senator suit_handmade clothing_2 piece set_Nigerian men outfit_Kaftan.jpeg" "african-suit.jpeg"
ren "images\men fashion\men red kaunda.jpeg" "men-kaunda.jpeg"
ren "images\men fashion\بدلة رجالية عادية من قميص كم طويل بسحاب أمامي….jpg" "arabic-suit.jpg"
ren "images\sports equipment\2Pcs_set World Soccer Referee Flag Fair Play Sports Match Football Linesman Europe Flags Referee.jpeg" "referee-flags.jpeg"
ren "images\sports equipment\12 Pcs Soccer Medals for Student Awards Kids Football Trophies Zinc Alloy 5cm Metal Prize.jpeg" "soccer-medals.jpeg"
ren "images\sports equipment\Armmanschette aus Eisseide, schnell trocknend, atmungsaktiv, UV-Schutz, Sportbekleidung,.jpeg" "arm-sleeves.jpeg"
ren "images\sports equipment\At Puffin Sports, we manufacture premium training….jpeg" "training-equipment.jpeg"
ren "images\sports equipment\Football Medals for Kids, 12-Pack of Silver Metal Medal with Tricolour Nylon Ribbon, Football Party Favours for Boys Children Adults.jpeg" "kids-football-medals.jpeg"
ren "images\sports equipment\Football Referee Flag with Carry bag coin Soccer….jpeg" "referee-flag.jpeg"
ren "images\sports equipment\Fußballsocken Aus Baumwolle Für Herren Einheitsgröße 39-45 Sportstrümpfe W_ 9 Fa.jpeg" "football-socks.jpeg"
ren "images\sports equipment\Gold Football Trophy On White Background, Gold Football Trophy, Soccer Trophy, Football PNG Transparent Image and Clipart for Free Download.jpeg" "gold-trophy.jpeg"
ren "images\sports equipment\Gold Star Crystal Award _ Golden Star Crystal Tower Trophy _ Star Award.jpeg" "gold-star-trophy.jpeg"
ren "images\sports equipment\Gold Trophy Vector Design Images, Gold Trophy, Gold Clipart, Trophies, Gold PNG Image For Free Download.jpeg" "gold-vector-trophy.jpeg"
ren "images\sports equipment\High Quality Pro Football Soccer Game Match Referee Card Umpire Judge Red Yellow Cards - AliExpress 18.jpeg" "referee-cards.jpeg"
ren "images\sports equipment\Large Gold Trophy Cup for Sports Tournaments, 38CM Metal Gold Trophies Party Favors, First Place Winner Award Trophies Cup for Soccer Football.jpeg" "large-gold-trophy.jpeg"
ren "images\sports equipment\Listos para apoyar nuestra selección en la Copa….jpeg" "team-support.jpeg"
ren "images\sports equipment\NUOBESTY Gold Award Trophy Cups First Place Winner Award Trophies Metal Medals For Big Spelling Bee Competitions Prizes Basketball Game 35_ 5CM.jpeg" "gold-award-trophy.jpeg"
ren "images\sports equipment\Outdoor Sports Soccer Goal Two-in-one suit Boys and Girls Basketball Stand Portable Soccer Goal.jpeg" "portable-goal.jpeg"
ren "images\sports equipment\Professional Football Jerseys 2025 Men's Referee Uniforms Short Pocket Soccer Tracksuits Thailand.jpeg" "referee-uniform.jpeg"
ren "images\sports equipment\Professional Men Referee Uniforms Soccer Men Football Jerseys Shorts Shirts Suit Pocket Tracksuits.jpeg" "men-referee-tracksuit.jpeg"
ren "images\sports equipment\Trofei Sports Cup Soccer Trophy Trophies Awards Football Medals Custom Mini Prize Winner Volleyball.jpeg" "sports-trophy.jpeg"
ren "images\maish school uniiform\British Style Striped Neck Tie for School Uniform….jpg" "striped-tie.jpg"
ren "images\maish school uniiform\Color_Blue _nPattern Type_Colorblock _nPattern….jpg" "colorblock.jpg"
ren "images\maish school uniiform\Get her set for school with our stylish lace-up….jpg" "lace-up-shoes.jpg"
ren "images\maish school uniiform\PRICES MAY VARY_ Hand Wash Only Modern.jpg" "hand-wash.jpg"
ren "images\maish school uniiform\PRICES MAY VARY_ Introducing our latest innovation….jpg" "latest-innovation.jpg"
ren "images\maish school uniiform\PRICES MAY VARY_ V-Neck Sweater Sweatshirt….jpg" "v-neck-sweater.jpg"
ren "images\maish school uniiform\School Shoes For Bata _ Shoes For Student Trends….jpg" "school-shoes.jpg"
ren "images\women clothing\100+ Unique Latest Ankara Styles for Ladies….jpg" "ankara-styles.jpg"
ren "images\women clothing\18055cm Candy Colored Neckerchief Long Scarf Solid Color Soft Scarves Shawls.jpeg" "candy-scarf.jpeg"
ren "images\women clothing\Buy OQQ Women 3 Piece Yoga Shorts Sexy High Waist….jpg" "yoga-shorts.jpg"
ren "images\women clothing\Cable Knitted Cardigan Sweater - Etsy.jpeg" "cardigan-sweater.jpeg"
ren "images\women clothing\CARACTÉRISTIQUES________ Type de tissu _ Fibre….jpg" "fabric-item.jpg"
ren "images\women clothing\Court-ready styles that balance professionalism….jpg" "court-dress.jpg"
ren "images\women clothing\Damespakset, jasje en kokerrok, blouse met strikdecoratie en splitrok, effenkleurig pak voor kantoor en vrijetijdskleding, lente_zomer, herfst.jpeg" "suit-set.jpeg"
ren "images\women clothing\Fabric_ Polyester_ The fabric is comfortable for….jpg" "polyester-wear.jpg"
ren "images\women clothing\Get ready to turn heads in this stunning floral….jpg" "floral-dress.jpg"
ren "images\women clothing\Kariertes Muster Damen Zweiteiler, Damen Jacke und Damen schmale gerade Röcke, für den täglichen Büroweg, eleganter Damenanzug.jpeg" "checkered-suit.jpeg"
ren "images\women clothing\Mayfair™ _ Luxus-Kaschmirschal - Dark green.jpeg" "luxury-scarf.jpeg"
ren "images\women clothing\Perfect balance between comfort and control for….jpg" "comfort-wear.jpg"
ren "images\women clothing\PRICES MAY VARY_ 【 Fabric 】_ 90% Polyester + 10%….jpg" "polyester-item.jpg"
ren "images\women clothing\PRICES MAY VARY_ Chic Design_This womens long….jpg" "long-dress.jpg"
ren "images\women clothing\PRICES MAY VARY_ Church Dress for Women Is Made Of….jpg" "church-dress.jpg"
ren "images\women clothing\PRICES MAY VARY_ Material-- Stretch Breathable….jpg" "stretch-wear.jpg"
ren "images\women clothing\ROTITA Lapel Black Long Sleeve Two Piece Suit….jpg" "two-piece-suit.jpg"
ren "images\women clothing\Stylish Dresses for Women _ Vacation, Casual, Wedding Guest & Resort Dresses.jpeg" "stylish-dress.jpeg"
ren "images\women clothing\Stylish Dresses for Women _ Vacation, Casual, Wedding Guest & Resort Dresses.jpg" "stylish-dress.jpg"
ren "images\women clothing\trouser suite.jpeg" "trouser-suit.jpeg"
ren "images\work wear\Custom Black Professional Executive Style Safety Vest - 3XL _ Black.jpeg" "safety-vest.jpeg"
ren "images\work wear\Shoes for Crews Guard Mid, Safety Shoes CE Certified S3 HRO WR SRC, Unisex Work Boots with Slip Resistant Outsole, Water Repellent Safe Work Shoes for Men and Women.jpeg" "safety-shoes.jpeg"
ren "images\work wear\Stock up on workwear here.jpeg" "workwear-stock.jpeg"
ren "images\work wear\Veste et pantalon de protection du travail en polycoton trempé pour hommes, vêtements de travail,.jpeg" "protection-clothes.jpeg"
ren "images\work wear\Conjunto Uniforme EPI Nr10 Segurança do Trabalho Mecanico Faixa Eletricista Refletiva Construção Obra Serviço.jpeg" "safety-uniform.jpeg"
ren "images\work wear\Glossy yellow hard hat with black chin strap isolated on transparent background.jpeg" "hard-hat.jpeg"
ren "images\work wear\The Wins Are Bigger.jpeg" "wins-bigger.jpeg"
ren "images\work wear\Overalls and Bibs.jpeg" "overalls-bibs.jpeg"
ren "images\work wear\Fort Workforce Safety Boots - Black _ 8.jpeg" "safety-boots.jpeg"
ren "images\Ankara styles.jpeg" "ankara-styles-main.jpeg"
ren "images\Blue Curtain Golden Floral Desing Background Wallpaper Image For Free Download - Pngtree.jpeg" "blue-curtain.jpeg"
ren "images\Cotton Bath Towel Adult Soft Absorbent Towels Bathroom Sets Large Beach Towel Hotel Spa Towels For.jpeg" "bath-towel-main.jpeg"
ren "images\Exploring the Role of a Security Guard Company in Fremont.jpeg" "security-guard.jpeg"
ren "images\FR Fashion Co_ 20 Men's Versatile Leather Duffel Bag - Brown.jpeg" "leather-duffel-main.jpeg"
ren "images\LABERDE on Instagram_ "Classic Casual Suit ??..jpg" "casual-suit.jpg"
ren "images\maish boutique.png" "maish-boutique.png"
ren "images\PRICES MAY VARY_ ?Western Style Denim Jacket..jpg" "denim-jacket.jpg"
ren "images\Classic men's suits outfit crafted to impress.jpeg" "classic-suit.jpeg"
ren "images\Hoodie banner design.jpeg" "hoodie-banner.jpeg"
ren "images\The Stearns & Foster Lux Estate Collection..jpg" "lux-mattress.jpg"
ren "images\Women's Vacation Romantic Elegant Ditsy Floral..jpg" "floral-dress-main.jpg"